### PR TITLE
Update to Prosody 0.9.11 and luarocks 2.4.1

### PR DESCRIPTION
**Pull request by zeen**

### CODE REVIEW

**Comment by chrisballinger** [comment]
This PR won't work properly due to lua51 issues, and still uses sha1.

See my PR: https://github.com/prosody/homebrew-prosody/pull/8/files

**Comment by Zash** [comment]
What Lua issues would that be?

**Comment by chrisballinger** [comment]
The default lua in homebrew is 5.2, which I've heard doesn't work with Prosody until 0.10. If you see my PR, I've pinned to Lua51 and am overriding the luasec rock to the last lua51 compatible version.

Also I fixed the package hashes to sha256, as sha1 is deprecated and gives warnings.

**Comment by Zash** [comment]
0.9.11 includes a compat fix for latest LuaSec.  It's not incompatible with Lua 5.1 itself, but with things that relied on the older way where modules are exported via globals.

**Comment by chrisballinger** [comment]
Oh okay great! I was going by some old mailing list thread and haven't seen anything about 0.9.11. If that's resolved, the only issue is that this PR should use sha256.

edit: Oh wait I misread. So 0.9.11 is still incompatible with Lua 5.2?

**Comment by zeen** [comment]
After a number of fixes, this PR runs as expected in a clean OS X VM.

**Pull request merged**
